spring:
  cloud:
    function:
      definition: emitSensorReading
    stream:
      poller:
        fixedDelay: 5000
      bindings:
        emitSensorReading-out-0:
          destination: sensor/temperature/fahrenheit
          binder: local_solace
      binders:
        local_solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO